---

- name: ensure can utils are installed and up to date 
  become: true 
  apt: 
    name: can-utils 
    state: latest
  tags: 
    - can_isotp


- name: install kernel headers for raspberry_pi
  become: true
  apt:
    name: raspberrypi-kernel-headers
    state: latest
  tags: 
    - can_isotp


# START OF INSTALLING CAN-ISOTP FROM HARTKOPP
- name: checkout hartkopp can-isotp from github to /etc/can-isotp
  become: true 
  git:
    repo: 'https://github.com/hartkopp/can-isotp.git'
    dest: /etc/can-isotp
    update: yes 
    #version: possibility to checkout specific version
  tags: 
    - can_isotp_install


- name: build kernel module in repositories root path
  become: true
  shell: make -C /lib/modules/$(uname -r)/build M=$(pwd) modules_install
  args:
    chdir: /etc/can-isotp
  tags: 
    - can_isotp_install


- name: execute command in repositories root path -> depmod 
  shell: depmod
  become: true 
  args:
    chdir: /etc/can-isotp
  tags:
    - can_isotp_install


- name: execute command in repositories root path -> modprobe can-isotp
  shell: modprobe can-isotp
  become: true 
  args:
    chdir: /etc/can-isotp
  tags:
    - can_isotp_install
# END OF INSTALLING CAN-ISOTP FROM HARTKOPP


- name: store results 
  shell: lsmod | grep can
  become: true 
  register: shell_result
  tags: 
    - can_isotp
    - can_isotp_install
    

- name: output results 
  debug:
    var: shell_result.stdout_lines
  tags: 
    - can_isotp
    - can_isotp_install


- name: set can1 bitrate
  shell: ip link set can1 type can bitrate "{{var_can1_bitrate}}" 
  become: true 
  tags:
    - can_isotp
    - set_up_can0_can1


- name: set up can1
  shell: ip link set up can1
  become: true 
  tags:
    - can_isotp
    - set_up_can0_can1


- name: set can0 bitrate
  shell: ip link set can0 type can bitrate "{{var_can0_bitrate}}" 
  become: true 
  tags:
    - can_isotp
    - set_up_can0_can1


- name: set up can0
  shell: ip link set up can0
  become: true 
  tags:
    - can_isotp
    - set_up_can0_can1

